version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"

  api-service:
    container_name: api-service
    image: docker-compose-api-service
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    ports:
      - "9001:9001"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-service
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"